src/encoreNav.json
Removes the visibility param. See #44 for more details.
=> chore(billing): remove visibility option

src/encoreNav.json
for the release of the ESX Rekick app this afternoon
=> feat(encoreNav): Add ESX Rekick to Support Automation

src/encoreNav.json
Retrying PR #37 now that the CDN caching has changed.
=> feat(encoreNav): Add search directive to WCB nav item.

src/encoreNav.json
Corresponding PR for the application code is [here](https://github.rackspace.com/dcx/load-balancer-service/pull/286) - as of now it has not been merged yet.
=> Add Load Balancer Service to Support Automation.

src/encoreNav.json
Requires https://github.com/rackerlabs/encore-ui/pull/706 to function correctly
=> chore(billing): add UK visibility option

src/encoreNav.json
=> feat(billing): Rename to Billing Search and add dropdown arrow styling

src/encoreNav.json
This PR is in place in preparation for the release of Load Balancer Service in Encore.
=> chore(lbs): Change url of Load Balancer Service.

README.md
1.  Path for softlink changed for encoreNav.json
2.   Patch in config changed for encoreNav.json
=> Updated documentation for successful installation of Nav

src/encoreNav.json
This would be a followup to #74
=> feat(ticketing): Add Mass Ticketing to Ticketing Navigation Menu

src/encoreNav.json
For https://jira.rax.io/browse/EOD-377
=> feat(VirtAdmin): Added virt children to nav

src/encoreNav.json
This adds the menu items to our new features for Beta to the main nav
=> feat(ticketing): Adding in ATS and Preset links

src/encoreNav.json
https://jira.rax.io/browse/EOD-220
=> feat(vcenter): EOD-220 show/hide subnav on toggle

src/encoreNav.json
https://jira.rax.io/browse/ETUI-633
https://jira.rax.io/browse/ETUI-675
https://jira.rax.io/browse/ETUI-673
https://jira.rax.io/browse/EN-1938
To be released **05/21/2015**
=> feat(accounts): Add Link to ticketing

src/encoreNav.json
EOD-220 show/hide subnav on toggle
https://jira.rax.io/browse/EOD-220
EOD-377 added virt children to nav
https://jira.rax.io/browse/EOD-377
@chriscantu @parlarjb @TheNando Waiting on CR.
=> [DO NOT MERGE] feat(vcenter): EOD-220 nav toggle, EOD-377 subnav

src/encoreNav.json
Also adds Infrastructure Manager to DCX.
=> feat(dcx): move Support Automation to DCX

src/encoreNav.json
Jira :https://jira.rax.io/browse/EN-2119
Front end : https://github.com/rackerlabs/encore-cloud-ui/pull/665
No DESIGN LGTM needed
=> feat(UI) EN-2119: add link to left nav for Cloud Backup

src/encoreNav.json
Added a separate Billing menu option.
=> Added a Billing menu option.

README.md
bame => name
(line 64, column 300 - might be hard to spot on the diff)
targetted => targeted
- QE LGTM not needed here
- DESIGN LGTM not needed here
=> docs(README): fix two typos

src/encoreNav.json
Reverts rackerlabs/encore-ui-nav#102
:grimacing: 
@nickburns2006 just tagging you so you know
=> Revert "fix(ticketing): Adding in childVisibility to Ticketing"

src/encoreNav.json
[JIRA EN-2252] (https://jira.rax.io/browse/EN-2252)
=> EN-2252 Cloud Monitoring nav link

src/encoreNav.json
Added the search option and renamed the name of the main menu option.
=> Added the search option and renamed the name of the main menu option.

src/encoreNav.json
jira:  https://jira.rax.io/browse/EN-2102
=> En 2102 cloud files navlink

src/encoreNav.json
=> Cloud Monitoring nav link

src/encoreNav.json
=> feat(cloud files) En-2102 add nav link for cloud files

src/encoreNav.json
Jira: https://jira.rax.io/browse/EN-2119
=> EN-2119 add cloud backup link to preprod

src/encoreNav.json
[ETUI-928](https://jira.rax.io/browse/ETUI-928)
[TQ UI PR](https://github.com/rackerlabs/encore-tq-ui/pull/435)
=> feat(tickets): Add My Customer Tickets Link

src/encoreNav.json
[JIRA story](https://jira.rax.io/browse/EN-2489)
=> feat(cloud-dns): Adds Cloud DNS as a child of Cloud nav

src/encoreNav.json
Need to rename and move the DNS nav
=> feat(cloud-dns): Changes Cloud DNS to DNS and moves up - STAGING

src/encoreNav.json
Jira: https://jira.rax.io/browse/EN-2119
=> feat(Cloud Backup) EN-2119 Add Cloud Backup Link Production

src/encoreNav.json
Add the DNS link to production nav per Teju's request.
=> feat(cloud-dns): Changes Cloud DNS to DNS and moves up

src/encoreNav.json
https://jira.rax.io/browse/ETUI-1109
=> feat(ticketing): ETUI-1109 add ticket search to nav

src/encoreNav.json
https://jira.rax.io/browse/ETUI-1109
=> ETUI-1109 - add ticket search to nav

src/encoreNav.json
Jira:  https://jira.rax.io/browse/EN-2779
Staging PR
=> chore(Navbar) EN-2779: Change Cloud to Cloud Products

src/encoreNav.json
Jira: https://jira.rax.io/browse/EN-2779
=> chore(Navbar) EN-2779: Rename Cloud to Cloud Products

src/encoreNav.json
This is a PR to place [Torq-ui](https://github.rackspace.com/dcx/torq-ui)  into base staging, please.
=> torq-ui-staging

src/encoreNav.json
@solim8r Waiting on CR to merge
=> ETUI-1109: add ticket search to nav

src/encoreNav.json
Adding Torq Navigation to Preprod.
=> torq-ui-preprod

src/encoreNav.json
Updates production navigation to include Torq UI.
=> torq-ui-production

src/encoreNav.json
JIRA: https://jira.rax.io/browse/EN-2867
=> feat(apiLimits) EN-2867: Nav element for API limits

src/encoreNav.json
Jira: https://jira.rax.io/browse/EN-2867
=> feat(apilimits) EN-2857: ApiLimits Nav element preprod

src/encoreNav.json
Jira: https://jira.rax.io/browse/ECUI-241
Nothing to see here just a simple reorder of products.
=> refactor(NavBar) ECUI-241: Alpha order cloud products

src/encoreNav.json
Jira: https://jira.rax.io/browse/ECUI-241
Again just reorder nothing else.
=> chore(navbar) ECUI-241: Alpha order cloud products preprod

src/encoreNav.json
Jira: https://jira.rax.io/browse/ECUI-241
=> chore(navBar) ECUI-241: swap 2 pairs and rename another

src/encoreNav.json
- Create 'Admin Tools' parent nav menu
- Create 'Recent Signups' child nav menu
=> Create 'Admin Tools' & 'Recent Signups' nav menu items

src/encoreNav.json
Jira: https://jira.rax.io/browse/ECUI-240
Added "logging & reports", added "activity log" landing page for new `encore-logging` repo, and renamed reports from accounts. 
```
Logging & Reports 
Audit History (renamed reports) 
Encore Activity Log
```
=> Ecui 240 logging reports nav group staging

src/encoreNav.json
Jira: https://jira.rax.io/browse/ECUI-240
Added "logging & reports", added "activity log" landing page for new `encore-logging` repo, and renamed reports from accounts. 
```
Logging & Reports 
Audit History (renamed reports) 
Encore Activity Log
```
=> feat(Navbar) ECUI-240: add logging & reports parent

src/encoreNav.json
Jira: https://jira.rax.io/browse/ECUI-240
Added "logging & reports", added "activity log" landing page for new `encore-logging` repo, and renamed reports from accounts. 
```
Logging & Reports 
Audit History (renamed reports) 
Encore Activity Log
```
=> feat(NavBar) ECUI-240: Add logging & Reports parent to navbar

src/encoreNav.json
Reverting this until the code for logging is deployed to production
=> revert logging reporting

src/encoreNav.json
Please leave this alone till Monday because thats when the actual page is going out.
=> fix(navbar) ECUI-25: logging route fix (master)

src/encoreNav.json
Update nav to make ACT visible for production environment. 
ACT has been deployed. 
(cherry picked from commit 304442112dd50644efa5961fc1740d7e2160d003)
=>     add ACT to nav for production

src/encoreNav.json
Jira: https://jira.rax.io/browse/ECUI-533
=> feat(navbar) ECUI-533: add Cloud Sites to navbar in Staging

src/encoreNav.json
Jira: https://jira.rax.io/browse/ECUI-533
=> feat(navbar) ECUI-534: add Cloud Sites to navbar in Preprod

src/encoreNav.json
Added in navigation items for Network Security to Genesis and Raven
=> Added Network Security Bar

src/encoreNav.json
Updates the link for networks for this story
[Jira](https://jira.rax.io/browse/ECUI-589)
=> Updates networks link

src/encoreNav.json
=> feat(navbar) ECUI-473: Display Cloud Sites on Left Nav - Production

src/encoreNav.json
Reverts rackerlabs/encore-ui-nav#172
=> Revert "feat(navbar) ECUI-473: Display Cloud Sites on Left Nav - Production"

src/encoreNav.json
For: [Jira](https://jira.rax.io/browse/ECUI-590) 
Already out to preprod:
[New Dbaas on Staging](https://staging.encore.rackspace.com/cloud/dbaas/323676/hub_cap/instances)
=> Updates nav.json

src/encoreNav.json
For preprod
[Dbaas on preprod](https://preprod.encore.rackspace.com/cloud/dbaas/323676/hub_cap/instances)
Before: `/cloud/323676/hub_cap/databases/instances`
After: `/cloud/dbaas/323676/hub_cap/instances`
=> Updates nav.json for dbaas

src/encoreNav.json
Gearing up for tomorrow's release of the newly pulled out dbaas repo
=> Updates nav.json for new dbaas on Prod

src/encoreNav.json
Nav change for UK Billing release.
=> feat(Billing): remove logic which hides billing for UK

src/encoreNav.json
* reduce TORQ nav from 4 to 3 navigation levels
=> fix(deepLink): refactor TORQ links - staging

src/encoreNav.json
* reduce TORQ nav from 4 to 3 navigation levels
=> fix(deepLink): refactor TORQ links - preprod

src/encoreNav.json
* reduce TORQ nav from 4 to 3 navigation levels
=> fix(deepLink): refactor TORQ links - master

src/encoreNav.json
https://jira.rax.io/browse/RTB-10
=> RTB-10: remove Cloud Sites nav (staging)

src/encoreNav.json
https://jira.rax.io/browse/RTB-57
=> RTB-57 - remove Cloud Sites nav (preprod)

src/encoreNav.json
Added ESS UI 2.0 links per mockups by RED:
https://rackspace.invisionapp.com/share/3Y7NURVSC#/screens/167069380
=> Added Support Service 2.0 links

src/encoreNav.json
https://jira.rax.io/browse/RTB-58
**Scheduled for release on Tuesday November 8th @ 1pm CST**
/cc @sfduerr
=> RTB-58 - chore(cloud sites): remove Cloud Sites nav (prod)

src/encoreNav.json
JIRA Story: 
https://jira.rax.io/browse/ACT-508
Screen shot using local config:
=> ACT-508_workflow_nav

src/encoreNav.json
Jira: https://jira.rax.io/browse/ACT-639
Desc: Changes to add navigation links for ACT workflows and Responsible Departments
=> add ACT nav links for workflow and responsible departments

package.json
This will fix the vulnerability notices we keep getting e-mailed.
=> chore(deps): Update lodash for security vulnerability

src/encoreNav.json
JIRA: https://jira.rax.io/browse/ALD-1589
=> Added nav schema for UCP

src/encoreNav.json
JIRA: https://jira.rax.io/browse/ALD-2081
=> Remove-Dcx-ImUi-Link

src/encoreNav.json
JIRA: https://jira.rax.io/browse/ALD-2081
=> removeImui
